### ISSUE TITLE
No NEEO Cloud or Album Art/Hue Meta Colours loading after install script

### ISSUE THREAD

**Issue by smarthomesydney** [jac459/neeo2021onward#2]
No NEEO Cloud or Album Art/Hue Meta Colours loading after install script.

Issue occurs after running the script and power cycling the brain (power plug removal)

Cloud Unreachable in Settings, About.

**Comment by Ton-O** [comment]
The problem was a missing userid for the timesync-daemon. 
This userid was probably removed by a system-update that replace /etc/passwd file (I will verify).
Adding the user&restarting service solved the problem. 
Also created missing home-directory for mosquito user. 
Changes will be committed in Beta #3

**Comment by Ton-O** [comment]
Fixed.
